CREATE TABLE `broker_information` (
`id` INTEGER,
`broker_name` TEXT,
`irdai_no` TEXT,
`created_at` TIMESTAMP,
`updated_at` TIMESTAMP,
`deleted_at` TIMESTAMP,
`broker_slug` TEXT,
`irdai_expiry_date` TIMESTAMP,
`cin_no` TEXT,
`email` TEXT,
`cc_email` TEXT,
`bcc_email` TEXT,
`contact_no` TEXT,
`mobile_no` TEXT,
`licence_no` TEXT,
`licence_expiry_date` TIMESTAMP,
`address` TEXT,
`logo` TEXT,
`fav_icon` TEXT,
`footer_content` TEXT,
`domain_name` TEXT,
`category` TEXT CHECK(category IN ('direct','reinsurance','composite'))
);

CREATE TABLE `server_master` (
`server_id` INTEGER,
`server_name` TEXT,
`server_type` TEXT CHECK(server_type IN ('Application','Database','RDS','Mongo','Redis','S3','Secrete Manager','SMTP')),
`server_status` TEXT CHECK(server_status IN ('Y','N')),
`app_host` TEXT,
`app_port` INTEGER,
`app_username` TEXT,
`app_password` TEXT,
`app_proxy_needed` TEXT CHECK(app_proxy_needed IN ('Y','N')),
`proxy_app_host` TEXT,
`proxy_app_port` INTEGER,
`proxy_app_username` TEXT,
`proxy_app_password` TEXT,
`db_host` TEXT,
`db_port` INTEGER,
`db_database` TEXT,
`db_username` TEXT,
`db_password` TEXT,
`db_proxy_needed` TEXT CHECK(db_proxy_needed IN ('Y','N')),
`proxy_db_host` TEXT,
`proxy_db_port` INTEGER,
`proxy_db_database` TEXT,
`proxy_db_username` TEXT,
`proxy_db_password` TEXT,
`rds_host` TEXT,
`rds_port` INTEGER,
`rds_database` TEXT,
`rds_username` TEXT,
`rds_password` TEXT,
`rds_proxy_needed` TEXT CHECK(rds_proxy_needed IN ('Y','N')),
`proxy_rds_host` TEXT,
`proxy_rds_port` INTEGER,
`proxy_rds_database` TEXT,
`proxy_rds_username` TEXT,
`proxy_rds_password` TEXT,
`mongo_host` TEXT,
`mongo_port` INTEGER,
`mongo_database` TEXT,
`mongo_username` TEXT,
`mongo_password` TEXT,
`mongo_allow_inavlid_certificates` TEXT CHECK(mongo_allow_inavlid_certificates IN ('Y','N')),
`mongo_retry_writes` TEXT,
`db_authentication_database` TEXT,
`redis_host` TEXT,
`redis_port` INTEGER,
`redis_password` TEXT,
`aws_default_region` TEXT,
`aws_bucket` TEXT,
`aws_s3_url` TEXT,
`aws_node` TEXT,
`manual` TEXT CHECK(manual IN ('Y','N')),
`aws_access_key_id` TEXT,
`aws_secret_access_key` TEXT,
`sm_default_region` TEXT,
`sm_server` TEXT,
`sm_manual` TEXT CHECK(sm_manual IN ('Y','N')),
`sm_access_key_id` TEXT,
`sm_secret_access_key` TEXT,
`mail_host` TEXT,
`mail_port` INTEGER,
`mail_username` TEXT,
`mail_password` TEXT,
`mail_from_address` TEXT,
`mail_from_name` TEXT,
`created_at` TIMESTAMP,
`updated_at` TIMESTAMP,
`deleted_at` TIMESTAMP
);

CREATE TABLE `enviroment_master` (
`enviroment_id` INTEGER,
`enviroment_name` TEXT,
`enviroment_slug` TEXT,
`enviroment_status` TEXT CHECK(enviroment_status IN ('Y','N')),
`created_at` TIMESTAMP,
`updated_at` TIMESTAMP,
`deleted_at` TIMESTAMP
);


CREATE TABLE `domain_instances_creation` (
  `instance_creation_id` INTEGER,
  `broker_id` INTEGER NOT NULL,
  `instance_mechanism` TEXT CHECK(instance_mechanism IN ('broker onboard','docker')) NOT NULL,
  `environment_id` INTEGER NOT NULL,
  `domain_name` TEXT NOT NULL,
  `frontend_pos_url` TEXT NOT NULL,
  `frontend_nonpos_url` TEXT NOT NULL,
  `fe_git_repo` TEXT DEFAULT NULL,
  `fe_server_id` TEXT DEFAULT NULL,
  `fe_git_branch` TEXT DEFAULT NULL,
  `frontend_url_description` TEXT DEFAULT NULL,
  `backend_url` TEXT DEFAULT NULL,
  `be_git_repo` TEXT DEFAULT NULL,
  `be_git_branch` TEXT DEFAULT NULL,
  `be_server_id` TEXT DEFAULT NULL,
  `backend_url_description` TEXT DEFAULT NULL,
  `ckyc_url` TEXT DEFAULT NULL,
  `ckyc_url_description` TEXT DEFAULT NULL,
  `ckyc_git_repo` TEXT DEFAULT NULL,
  `ckyc_git_branch` TEXT DEFAULT NULL,
  `ckyc_server_id` TEXT DEFAULT NULL,
  `instance_creation_status` TEXT CHECK(instance_creation_status IN ('Y','N')) NOT NULL,
  `created_at` TEXT DEFAULT NULL,
  `updated_at` TEXT DEFAULT NULL,
  `deleted_at` TEXT DEFAULT NULL,
  `deployment_status` TEXT CHECK(deployment_status IN ('in_queue','started','completed','failed')) NOT NULL
);
