INSERT INTO broker_information (id, broker_name, irdai_no, created_at, updated_at, deleted_at, broker_slug, irdai_expiry_date, cin_no, email, cc_email, bcc_email, contact_no, mobile_no, licence_no, licence_expiry_date, address, logo, fav_icon, footer_content, domain_name, category) VALUES ('1', 'PAYTM BROKER', '656', '2024-05-17 18:35:32', '2024-05-17 18:35:32', NULL, 'paytm', '2024-06-01 00:00:00', '4545v456678n7bg', 'paytm@fyntune.com', 'tadmwein@fyntune.com', 'tadsdsdin@fyntune.com', '7789678908', '8787878788', '58765g5hhhjghj', '2024-05-22 00:00:00', 'sdfsfsdfsdf', 'broker_logo/logo_1715951132.png', 'broker_favicon/fav_icon_1715951132.png', 'Footer ContentFooter ContentFooter ContentFooter ContentFooter ContentFooter ContentFooter ContentFooter ContentFooter Content', 'https://paytm.fynity.in/', 'direct');

INSERT INTO server_master (server_id, server_name, server_type, server_status, app_host, app_port, app_username, app_password, app_proxy_needed, proxy_app_host, proxy_app_port, proxy_app_username, proxy_app_password, db_host, db_port, db_database, db_username, db_password, db_proxy_needed, proxy_db_host, proxy_db_port, proxy_db_database, proxy_db_username, proxy_db_password, rds_host, rds_port, rds_database, rds_username, rds_password, rds_proxy_needed, proxy_rds_host, proxy_rds_port, proxy_rds_database, proxy_rds_username, proxy_rds_password, mongo_host, mongo_port, mongo_database, mongo_username, mongo_password, mongo_allow_inavlid_certificates, mongo_retry_writes, db_authentication_database, redis_host, redis_port, redis_password, aws_default_region, aws_bucket, aws_s3_url, aws_node, manual, aws_access_key_id, aws_secret_access_key, sm_default_region, sm_server, sm_manual, sm_access_key_id, sm_secret_access_key, mail_host, mail_port, mail_username, mail_password, mail_from_address, mail_from_name, created_at, updated_at, deleted_at) VALUES ('1', 'Paytm App server', 'Application', 'Y', '678.678.6786', '8787', 'admin', '123132', NULL, '89.789.689.98', '989', 'admin1', '123', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2024-05-17 18:36:45', '2024-05-17 18:36:45', NULL);
INSERT INTO server_master (server_id, server_name, server_type, server_status, app_host, app_port, app_username, app_password, app_proxy_needed, proxy_app_host, proxy_app_port, proxy_app_username, proxy_app_password, db_host, db_port, db_database, db_username, db_password, db_proxy_needed, proxy_db_host, proxy_db_port, proxy_db_database, proxy_db_username, proxy_db_password, rds_host, rds_port, rds_database, rds_username, rds_password, rds_proxy_needed, proxy_rds_host, proxy_rds_port, proxy_rds_database, proxy_rds_username, proxy_rds_password, mongo_host, mongo_port, mongo_database, mongo_username, mongo_password, mongo_allow_inavlid_certificates, mongo_retry_writes, db_authentication_database, redis_host, redis_port, redis_password, aws_default_region, aws_bucket, aws_s3_url, aws_node, manual, aws_access_key_id, aws_secret_access_key, sm_default_region, sm_server, sm_manual, sm_access_key_id, sm_secret_access_key, mail_host, mail_port, mail_username, mail_password, mail_from_address, mail_from_name, created_at, updated_at, deleted_at) VALUES ('2', 'Paytm App server1', 'Database', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '35.3454.435.', '455', 'demodb', 'admin2', '123', NULL, '879.789.789', '8989', 'db2', 'admin3', '123', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2024-05-17 18:40:51', '2024-05-18 12:48:11', NULL);

INSERT INTO enviroment_master (enviroment_id, enviroment_name, enviroment_slug, enviroment_status, created_at, updated_at, deleted_at) VALUES ('1', 'UAT', 'uat', 'Y', '2024-05-17 18:37:38', '2024-05-17 18:37:38', NULL);

INSERT INTO domain_instances_creation (instance_creation_id, broker_id, instance_mechanism, server_id, environment_id, domain_name, frontend_pos_url, frontend_nonpos_url, frontend_url_description, backend_pos_url, backend_nonpos_url, backend_url_description, ckyc_url, ckyc_url_description, instance_creation_status, created_at, updated_at, deleted_at, deployment_status) VALUES ('1', '1', 'broker onboard', '1,2', '1', 'https://paytm.fynity.in/', 'https://paytm.fynity.in/f/pos', 'https://paytm.fynity.in/', 'sdfsdf', 'https://paytm.fynity.in/b/pos', 'https://paytm.fynity.in/', 'sdfsdfsdf', 'https://paytm.fynity.in/c/', 'sdfsdfsdf', 'Y', '2024-05-17 18:38:19', '2024-05-23 17:07:03', NULL, 'in_queue');

